# Generated by Django 4.1 on 2022-08-22 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsapp', '0004_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='slug',
            field=models.SlugField(default=1, max_length=60, unique=True),
            preserve_default=False,
        ),
    ]
