# Generated by Django 3.2.14 on 2022-07-15 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyersapp', '0002_buyer_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='buyers_avatars', verbose_name='аватар'),
        ),
    ]
