# Generated by Django 3.2.14 on 2022-07-15 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyersapp', '0003_alter_buyer_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='age',
        ),
        migrations.AddField(
            model_name='buyer',
            name='birthday',
            field=models.PositiveIntegerField(default=19920703, verbose_name='дата рождения'),
            preserve_default=False,
        ),
    ]
