# Generated by Django 3.2.14 on 2022-07-19 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyersapp', '0006_buyer_birthday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='birthday',
        ),
        migrations.AddField(
            model_name='buyer',
            name='age',
            field=models.PositiveIntegerField(default=18, verbose_name='возраст'),
            preserve_default=False,
        ),
    ]
